export const REQUEST_VIDEO = 'REQUEST_VIDEO';
export const RECEIVE_VIDEO = 'RECEIVE_VIDEO';
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const RECEIVE_MORE_SEARCH = 'RECEIVE_MORE_SEARCH';
export const REQUEST_CHANNEL_THUMBNAIL = 'REQUEST_CHANNEL_THUMBNAIL';
export const RECEIVE_CHANNEL_THUMBNAIL = 'RECEIVE_CHANNEL_THUMBNAIL';
